apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wmashal/argocd-congigs.git
    targetRevision: HEAD
    path: dev

  # <namespace>.default.svc - kubectl get svc - becuase the ArgoCD inside the cluster it can connect to the ClusterIP svc type
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp # if this namespace not exist so we add a policy to create it see the following lines

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    # these options by default are disabled
    # two direction sync argo -> cluster and cluster -> argo
    # pull in 3 minutes interval by default to change this you can define a Git webhook
    automated:
      selfHeal: true # undo any changes done direct in the cluster
      prune: true # sync with any changes done on the Git repo
